---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Upgrade installed packages
  ansible.builtin.apt:
    upgrade: dist

- name: Check if reboot is required
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: common_reboot_required

- name: Reboot server if required
  ansible.builtin.reboot:
    reboot_timeout: 900
    test_command: whoami
  when: common_reboot_required.stat.exists
