---
- name: Get Traefik container info
  community.docker.docker_container_info:
    name: "{{ traefik_settings.container_name }}"
  register: traefik_container
  when: not ansible_check_mode


- name: Verify Traefik is running
  ansible.builtin.assert:
    that:
      - traefik_container.exists
      - traefik_container.container.State.Running
    success_msg: "Traefik container instance verified running perfe."
    fail_msg: "Traefik container is missing or failed to start up cleanly."
  when: not ansible_check_mode
